### ISSUE TITLE
Some points on the plane that should be in some triangle aren't in any triangle

### ISSUE THREAD

**Issue by Barteks2x** [jdiemke/delaunay-triangulator#2]
I wanted to use this library to triangulate data for terrain generation to interpolate it using method described here: https://classes.soe.ucsc.edu/cmps160/Fall10/resources/barycentricInterpolation.pdf

As a test, I added 3 points that make a triangle with different color assigned to each vertex, and one vertex for each corner of my image.

I used the same code as in TriangleSoup to search for triangle that is in a point and this is the result I got:

![result](https://user-images.githubusercontent.com/1349112/33804881-78bd3cb8-ddae-11e7-8fb6-b700043edf52.png)

As you can see there are points that aren't in any of the triangles.

**Comment by jdiemke** [comment]
That is perfectly fine since some points fall onto the triangles edges and hence are not contained inside a triangle. Take a look into `DelaunayTriangulator.java`:
`  Triangle2D triangle = triangleSoup.findContainingTriangle(pointSet.get(i));

            if (triangle == null) {
                /**
                 * If no containing triangle exists, then the vertex is not
                 * inside a triangle (this can also happen due to numerical
                 * errors) and lies on an edge. In order to find this edge we
                 * search all edges of the triangle soup and select the one
                 * which is nearest to the point we try to add. This edge is
                 * removed and four new edges are added.
                 */`
