### ISSUE TITLE
Maven/Gradle Repo

### ISSUE THREAD

**Issue by smileprem** [jdiemke/delaunay-triangulator#3]
Hi - Is this library available for download from maven central?

**Comment by jdiemke** [comment]
No it is not. Sounds like a good idea.

**Comment by smileprem** [comment]
Thanks. Could you please update us when it is available?

**Comment by phaus** [comment]
See Pull Request :-).

**Comment by hageldave** [comment]
Hey, great work! I'd like to ask if you could put this on maven-central, e.g. [like so](https://dzone.com/articles/publish-your-artifacts-to-maven-central)?
I know that @phaus is hosting this project on his own nexus, however I'm allergic to custom repositories for their uncertain lifespan (no offense).

I'd love to use your project within my plotting library and using an artifact from maven central would be a blast.
